name: Run NodePay-1 Script

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 */1 * * *' # Runs every 4 hours

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'

      - name: Install Playwright
        run: npm install playwright && npx playwright install chromium

      - name: Install Xvfb (GUI Emulator)
        run: sudo apt update && sudo apt install -y xvfb

      - name: Clear old NodePay profile
        run: rm -rf /home/runner/Nodepay/nodepay_1

      - name: Clear old extension files
        run: rm -rf /home/runner/Nodepay/extension_1

      - name: Extract Chromium Profile
        run: |
          mkdir -p /home/runner/Nodepay/nodepay_1
          tar -xzvf nodepay_1-profile.tar.gz -C /home/runner/Nodepay/nodepay_1

      - name: Extract Extension
        run: |
          mkdir -p /home/runner/Nodepay/extension
          tar -xzvf extension_1-profile.tar.gz -C /home/runner/Nodepay/extension

      - name: Start Xvfb (Simulate GUI)
        run: Xvfb :99 -screen 0 1920x1080x24 &

      - name: Run NodePay script
        run: node nodepay-1.js
        env:
          DISPLAY: ':99.0'  # Use Xvfb display for GUI support
